spring.application.name=auth-service

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.private-key-path=classpath:keys/private.pem
jwt.public-key-path=classpath:keys/public.pem
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
